apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kabinad24/kub-dep-users:latest
          env:
            - name: AUTH_ADDRESS
              #value: "10.100.39.136"
              value: "auth-service.default"